### ISSUE TITLE
Update tests/* to use regtest instead of testnet

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-reserves#14]
We're getting some test failures because tests are running against testnet and either the test wallets don't have sufficient funds or some network issues talking to electrum.blockstream.info.  We should be able to use the [`electrsd`](https://github.com/RCasatta/electrsd) crate to do these integration tests with a local regtest nodes.

**Comment by ulrichard** [comment]
Yes, I thought the same. Just didn't have time to implement it yet.
It may also be that somebody stole the Testnet coins, as the private keys are included in the tests.

**Comment by notmandatory** [comment]
Not sure if it's the testnet coins getting stolen since all I had to do was re-run the tests on github to get it to work.. could also be some timeout with the github actions and/or blockstream testnet electrum. But either way best to move to regtest.

**Comment by ulrichard** [comment]
I started working on that:
https://github.com/weareseba/bdk-reserves/tree/feature/regtest

**Comment by notmandatory** [comment]
Fixed by #15
