### ISSUE TITLE
Create proof panics instead of returning error when the wallet has no balance

### ISSUE THREAD

**Issue by sebastianmontero** [bitcoindevkit/bdk-reserves#22]
Hi

Why is unwrap used in [this](https://github.com/bitcoindevkit/bdk-reserves/blob/b4bef5204fe4a66b2e1b285e6a126e2be233a42b/src/reserves.rs#L137) line of the create_proof method, instead of returning an error? So as to allow the calling application to handle the error.

Thanks,

**Comment by ulrichard** [comment]
That was not intentional, but an oversight from converting the code from prototyping stage to production. 
Thanks for reporting.
