### ISSUE TITLE
Get bdk-reserves under bdk project

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bdk-reserves#9]
Opening up this issue to carry the conversation for getting bdk-reserves into bdk project.. There are few breaking changes coming up in bdk `v0.21.0` too.. Getting this project under bdk will help speedup bdk version upgrades, which will in turn help in bdk-cli version upgrades.. 

Tagging @notmandatory for visibility..

**Comment by notmandatory** [comment]
@ulrichard I'll put this on the agenda for our next bdk team chat, I think you'll need to give me admin rights on the bdk-reserves repo, then I can transfer it to the bitcoindevkit org in github. Once there you can keep your admin rights on it too.
